### ISSUE TITLE
[회원찾기/아이디 찾기] 

### ISSUE THREAD

**Issue by LEE2302** [codestates-seb/seb43_main_007#18]
- [x] 이름과 가상의 주민번호를 입력받을 칸을 만듭니다.
- [x] 입력받은 데이터로 요청을 보냅니다.
- [x] 유효성 검사를 합니다.(올바르면 아이디 알려주기, 틀리면 틀린 처리해주기)

예상 구현 시간
- 3hours

**Comment by kimsh322** [comment]
완성
